// THIS CODE WAS GENERATED BY ALARMCREATOR.v2
// DO NOT MODIFY IT MANUALLY - IT SHOULD BE REGENERATED

namespace PE.Common
{
    public static class ModuleAlarmDefs
    {

        /// <summary>
        /// Alarm definition for AlarmId: 40681
        /// MESSAGE FORMAT: Error of processing L3 Transfer Table
        /// </summary>
        public const string AlarmCode_ACTransferDataFromTransferTableToAdapter = "ADB001";

        /// <summary>
        /// Alarm definition for AlarmId: 40682
        /// MESSAGE FORMAT: Timeout in transfer table
        /// </summary>
        public const string AlarmCode_ADBTimeout = "ADB002";

        /// <summary>
        /// Alarm definition for AlarmId: 40680
        /// MESSAGE FORMAT: Error while updating Delay Catalogue
        /// </summary>
        public const string AlarmCode_ACDelayCatalogueUpdate = "DLS001";

        /// <summary>
        /// Alarm definition for AlarmId: 40672
        /// MESSAGE FORMAT: Error while updating Defect Catalogue
        /// </summary>
        public const string AlarmCode_ACDefectCatalogueUpdate = "MVH001";

        /// <summary>
        /// Alarm definition for AlarmId: 40673
        /// MESSAGE FORMAT: RawMaterial with external id:{0} not exist
        /// PARAMETERS: {L1 Material Id}
        /// </summary>
        public const string AlarmCode_RawMaterialNotExist = "MVH002";

        /// <summary>
        /// Alarm definition for AlarmId: 40674
        /// MESSAGE FORMAT: Saving of scrapping RawMaterial with external id:{0} failed
        /// PARAMETERS: {L1 External Id}
        /// </summary>
        public const string AlarmCode_ErrorDuringSave = "MVH003";

        /// <summary>
        /// Alarm definition for AlarmId: 40675
        /// MESSAGE FORMAT: Set as scrap {0} raw material with external id :{1} failed
        /// PARAMETERS: {Scrap Type, L1 external Id}
        /// </summary>
        public const string AlarmCode_MarkAsScrap = "MVH004";

        /// <summary>
        /// Alarm definition for AlarmId: 40676
        /// MESSAGE FORMAT: Cutting raw material with external id :{0} failed
        /// PARAMETERS: {L1 external Id}
        /// </summary>
        public const string AlarmCode_CutMaterial = "MVH005";

        /// <summary>
        /// Alarm definition for AlarmId: 40677
        /// MESSAGE FORMAT: Creating raw material failed
        /// </summary>
        public const string AlarmCode_CreateRawMaterial = "MVH006";

        /// <summary>
        /// Alarm definition for AlarmId: 40678
        /// MESSAGE FORMAT: Division Material {0} Failed
        /// PARAMETERS: {L1 external Id}
        /// </summary>
        public const string AlarmCode_DivideMaterial = "MVH007";

        /// <summary>
        /// Alarm definition for AlarmId: 40679
        /// MESSAGE FORMAT: Manager triggered error on init
        /// </summary>
        public const string AlarmCode_ManagerInitError = "MVH008";

        /// <summary>
        /// Alarm definition for AlarmId: 40683
        /// MESSAGE FORMAT: On material charge auto connecting L1 Material With L3 thrown unexpected error
        /// </summary>
        public const string AlarmCode_ConnectRawMaterialWithPRMMaterial = "MVH009";

        /// <summary>
        /// Alarm definition for AlarmId: 40689
        /// MESSAGE FORMAT: Set as finished raw material with external id : failed
        /// </summary>
        public const string AlarmCode_MarkAsFinished = "MVH010";

        /// <summary>
        /// Alarm definition for AlarmId: 40665
        /// MESSAGE FORMAT: Critical error when adding work order [id:{0}] to schedule
        /// PARAMETERS: {WorkOrderId}
        /// </summary>
        public const string AlarmCode_WorkOrderNotAddedToSchedule = "PPL001";

        /// <summary>
        /// Alarm definition for AlarmId: 40666
        /// MESSAGE FORMAT: Critical error when adding work order [id: {0}] to schedule
        /// PARAMETERS: {WorkOrderId}
        /// </summary>
        public const string AlarmCode_ToManyItemsInSchedule = "PPL002";

        /// <summary>
        /// Alarm definition for AlarmId: 40667
        /// MESSAGE FORMAT: Critical error when deleting item from schedule [scheduleId: {0}, workOrderId: {1}]
        /// PARAMETERS: {ScheduleId, WorkOrderId}
        /// </summary>
        public const string AlarmCode_DeleteItemFromSchedule = "PPL003";

        /// <summary>
        /// Alarm definition for AlarmId: 40668
        /// MESSAGE FORMAT: Warning - can't swap items. No item to change position near position {0}
        /// PARAMETERS: {scheduleItem.OrderSeq}
        /// </summary>
        public const string AlarmCode_NoItemToSwap = "PPL004";

        /// <summary>
        /// Alarm definition for AlarmId: 40669
        /// MESSAGE FORMAT: Critical error appears while test work order was beeing saved into DB - changes not saved
        /// </summary>
        public const string AlarmCode_SavingError = "PPL005";

        /// <summary>
        /// Alarm definition for AlarmId: 40670
        /// MESSAGE FORMAT: Error during processing create test work order function - unexpected error may happend
        /// </summary>
        public const string AlarmCode_CreateTestWorkOrder = "PPL006";

        /// <summary>
        /// Alarm definition for AlarmId: 40671
        /// MESSAGE FORMAT: Given number of materials in impropper
        /// </summary>
        public const string AlarmCode_ImproperNumberOfMaterials = "PPL007";

        /// <summary>
        /// Alarm definition for AlarmId: 40687
        /// MESSAGE FORMAT: Work Order schedule may be empty
        /// </summary>
        public const string AlarmCode_EmptySchedule = "PPL008";

        /// <summary>
        /// Alarm definition for AlarmId: 40688
        /// MESSAGE FORMAT: Request about next material in schedule thrown unexpected error
        /// </summary>
        public const string AlarmCode_RequestFirstMaterialInProductionSchedule = "PPL009";

        /// <summary>
        /// Alarm definition for AlarmId: 40659
        /// MESSAGE FORMAT: Work order [id: {0}] status don't allow it to update
        /// PARAMETERS: {WorkOrderId}
        /// </summary>
        public const string AlarmCode_WorkOrderNotUpdatable = "PRM001";

        /// <summary>
        /// Alarm definition for AlarmId: 40660
        /// MESSAGE FORMAT: Critical error when creating work order [name: {0}]
        /// PARAMETERS: {WorkOrderName}
        /// </summary>
        public const string AlarmCode_WorkOrderNotCreated = "PRM002";

        /// <summary>
        /// Alarm definition for AlarmId: 40661
        /// MESSAGE FORMAT: Error while updating Steelgrade
        /// </summary>
        public const string AlarmCode_SteelgradeUpdate = "PRM003";

        /// <summary>
        /// Alarm definition for AlarmId: 40662
        /// MESSAGE FORMAT: Error while updating Material Catalogue
        /// </summary>
        public const string AlarmCode_MaterialCatalogueUpdate = "PRM004";

        /// <summary>
        /// Alarm definition for AlarmId: 40663
        /// MESSAGE FORMAT: Error while updating Product Catalogue
        /// </summary>
        public const string AlarmCode_ProductCatalogueUpdate = "PRM005";

        /// <summary>
        /// Alarm definition for AlarmId: 40664
        /// MESSAGE FORMAT: Product Catalogue could not be found
        /// </summary>
        public const string AlarmCode_ProductCatalogueNotFound = "PRM006";

        /// <summary>
        /// Alarm definition for AlarmId: 40686
        /// MESSAGE FORMAT: Work Order Schedule is empty
        /// </summary>
        public const string AlarmCode_EmptyWorkOrderList = "PRM007";

        /// <summary>
        /// Alarm definition for AlarmId: 40684
        /// MESSAGE FORMAT: Error During Sale PRM table
        /// </summary>
        public const string AlarmCode_ErrurDuringSave = "PRM008";

        /// <summary>
        /// Alarm definition for AlarmId: 40685
        /// MESSAGE FORMAT: Searching first not connected material in schedule thrown unexpected error
        /// </summary>
        public const string AlarmCode_FindFirstFreeScheduledMaterial = "PRM009";

        /// <summary>
        /// Alarm definition for AlarmId: 40690
        /// MESSAGE FORMAT: Material connected with RawMaterial {0} not found
        /// PARAMETERS: {RawMaterialId}
        /// </summary>
        public const string AlarmCode_ProductNotFound = "PRM010";

        /// <summary>
        /// Alarm definition for AlarmId: 40691
        /// MESSAGE FORMAT: Critical error when creating product for RawMaterial {0}
        /// PARAMETERS: {RawMaterialId}
        /// </summary>
        public const string AlarmCode_ProductCreationFailed = "PRM011";

        /// <summary>
        /// Alarm definition for AlarmId: 40693
        /// MESSAGE FORMAT: Given list of structure telegram values is empty - telegram not exist in db
        /// </summary>
        public const string AlarmCode_EmptyTelegramValuesList = "STP001";

        /// <summary>
        /// Alarm definition for AlarmId: 40694
        /// MESSAGE FORMAT: Wrong telegram id {0}
        /// PARAMETERS: {TelegramId}
        /// </summary>
        public const string AlarmCode_NotExistingTelegram = "STP002";

        /// <summary>
        /// Alarm definition for AlarmId: 40695
        /// MESSAGE FORMAT: Critical error when processing manager setup configuration for telegram id {0}
        /// PARAMETERS: {TelegramId}
        /// </summary>
        public const string AlarmCode_TelegramSetupError = "STP003";

        /// <summary>
        /// Alarm definition for AlarmId: 40692
        /// MESSAGE FORMAT: Test Text 01
        /// </summary>
        public const string AlarmCode_Test = "Test1";

    }
}
