CREATE TABLE [dbo].[PRMSteelgradeChemicalCompositions] (
    [FKSteelgradeId] BIGINT     NOT NULL,
    [CreatedTs]      DATETIME   CONSTRAINT [DF_SteelgradeChemicalCompositions_CreatedTs] DEFAULT (getdate()) NOT NULL,
    [LastUpdateTs]   DATETIME   CONSTRAINT [DF_SteelgradeChemicalCompositions_LastUpdateTs] DEFAULT (getdate()) NOT NULL,
    [FeMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_FeMin] DEFAULT ((0)) NOT NULL,
    [FeMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_FeMax] DEFAULT ((0)) NOT NULL,
    [CMin]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_CMin] DEFAULT ((0)) NOT NULL,
    [CMax]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_CMax] DEFAULT ((0)) NOT NULL,
    [MnMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_MnMin] DEFAULT ((0)) NOT NULL,
    [MnMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_MnMax] DEFAULT ((0)) NOT NULL,
    [CrMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_CrMin] DEFAULT ((0)) NOT NULL,
    [CrMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_CrMax] DEFAULT ((0)) NOT NULL,
    [MoMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_MoMin] DEFAULT ((0)) NOT NULL,
    [MoMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_MoMax] DEFAULT ((0)) NOT NULL,
    [VMin]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_VMin] DEFAULT ((0)) NOT NULL,
    [VMax]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_VMax] DEFAULT ((0)) NOT NULL,
    [NiMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_NiMin] DEFAULT ((0)) NOT NULL,
    [NiMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_NiMax] DEFAULT ((0)) NOT NULL,
    [CoMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_CoMin] DEFAULT ((0)) NOT NULL,
    [CoMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_CoMax] DEFAULT ((0)) NOT NULL,
    [SiMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_SiMin] DEFAULT ((0)) NOT NULL,
    [SiMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_SiMax] DEFAULT ((0)) NOT NULL,
    [PMin]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_PMin] DEFAULT ((0)) NOT NULL,
    [PMax]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_PMax] DEFAULT ((0)) NOT NULL,
    [SMin]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_SMin] DEFAULT ((0)) NOT NULL,
    [SMax]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_SMax] DEFAULT ((0)) NOT NULL,
    [CuMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_CuMin] DEFAULT ((0)) NOT NULL,
    [CuMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_CuMax] DEFAULT ((0)) NOT NULL,
    [NbMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_NbMin] DEFAULT ((0)) NOT NULL,
    [NbMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_NbMax] DEFAULT ((0)) NOT NULL,
    [AlMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_AlMin] DEFAULT ((0)) NOT NULL,
    [AlMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_AlMax] DEFAULT ((0)) NOT NULL,
    [NMin]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_NMin] DEFAULT ((0)) NOT NULL,
    [NMax]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_NMax] DEFAULT ((0)) NOT NULL,
    [CaMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_CaMin] DEFAULT ((0)) NOT NULL,
    [CaMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_CaMax] DEFAULT ((0)) NOT NULL,
    [BMin]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_BMin] DEFAULT ((0)) NOT NULL,
    [BMax]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_BMax] DEFAULT ((0)) NOT NULL,
    [TiMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_TiMin] DEFAULT ((0)) NOT NULL,
    [TiMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_TiMax] DEFAULT ((0)) NOT NULL,
    [SnMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_SnMin] DEFAULT ((0)) NOT NULL,
    [SnMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_SnMax] DEFAULT ((0)) NOT NULL,
    [OMin]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_OMin] DEFAULT ((0)) NOT NULL,
    [OMax]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_OMax] DEFAULT ((0)) NOT NULL,
    [HMin]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_HMin] DEFAULT ((0)) NOT NULL,
    [HMax]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_HMax] DEFAULT ((0)) NOT NULL,
    [WMin]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_WMin] DEFAULT ((0)) NOT NULL,
    [WMax]           FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_WMax] DEFAULT ((0)) NOT NULL,
    [PbMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_PbMin] DEFAULT ((0)) NOT NULL,
    [PbMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_PbMax] DEFAULT ((0)) NOT NULL,
    [ZnMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_ZnMin] DEFAULT ((0)) NOT NULL,
    [ZnMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_ZnMax] DEFAULT ((0)) NOT NULL,
    [AsMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_AsMin] DEFAULT ((0)) NOT NULL,
    [AsMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_AsMax] DEFAULT ((0)) NOT NULL,
    [MgMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_MgMin] DEFAULT ((0)) NOT NULL,
    [MgMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_MgMax] DEFAULT ((0)) NOT NULL,
    [SbMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_SbMin] DEFAULT ((0)) NOT NULL,
    [SbMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_SbMax] DEFAULT ((0)) NOT NULL,
    [BiMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_BiMin] DEFAULT ((0)) NOT NULL,
    [BiMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_BiMax] DEFAULT ((0)) NOT NULL,
    [TaMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_TaMin] DEFAULT ((0)) NOT NULL,
    [TaMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_TaMax] DEFAULT ((0)) NOT NULL,
    [ZrMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_ZrMin] DEFAULT ((0)) NOT NULL,
    [ZrMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_ZrMax] DEFAULT ((0)) NOT NULL,
    [CeMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_CeMin] DEFAULT ((0)) NOT NULL,
    [CeMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_CeMax] DEFAULT ((0)) NOT NULL,
    [TeMin]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_TeMin] DEFAULT ((0)) NOT NULL,
    [TeMax]          FLOAT (53) CONSTRAINT [DF_PRMSteelgradeChemicalCompositions_TeMax] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SteelgradeChemicalCompositions] PRIMARY KEY CLUSTERED ([FKSteelgradeId] ASC),
    CONSTRAINT [FK_SteelgradeChemicalCompositions_Steelgrades] FOREIGN KEY ([FKSteelgradeId]) REFERENCES [dbo].[PRMSteelgrades] ([SteelgradeId]) ON DELETE CASCADE
);



