//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLSDelayCatalogue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DLSDelayCatalogue()
        {
            this.DLSDelayCatalogue1 = new HashSet<DLSDelayCatalogue>();
            this.DLSDelays = new HashSet<DLSDelay>();
        }
    
        public long DelayCatalogueId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public string DelayCatalogueCode { get; set; }
        public string DelayCatalogueName { get; set; }
        public string DelayCatalogueDescription { get; set; }
        public bool IsActive { get; set; }
        public bool IsDefault { get; set; }
        public double StdDelayTime { get; set; }
        public Nullable<long> FKDelayCatalogueCategoryId { get; set; }
        public Nullable<long> ParentDelayCatalogueId { get; set; }
        public short IsPlanned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DLSDelayCatalogue> DLSDelayCatalogue1 { get; set; }
        public virtual DLSDelayCatalogue DLSDelayCatalogue2 { get; set; }
        public virtual DLSDelayCatalogueCategory DLSDelayCatalogueCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DLSDelay> DLSDelays { get; set; }
    }
}
