//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLSDelay
    {
        public long DelayId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public long FKDelayCatalogueId { get; set; }
        public Nullable<long> FKRawMaterialId { get; set; }
        public string FKUserId { get; set; }
        public System.DateTime DelayStart { get; set; }
        public Nullable<System.DateTime> DelayEnd { get; set; }
        public string UserComment { get; set; }
        public bool IsPlanned { get; set; }
    
        public virtual DLSDelayCatalogue DLSDelayCatalogue { get; set; }
        public virtual MVHRawMaterial MVHRawMaterial { get; set; }
    }
}
