//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventType
    {
        public long EventTypeId { get; set; }
        public string EventTypeCode { get; set; }
        public string EventTypeName { get; set; }
        public string EventTypeDescription { get; set; }
        public string HMIIcon { get; set; }
        public string HMIColor { get; set; }
        public string HMILink { get; set; }
        public bool IsEditable { get; set; }
    }
}
