//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMIRefreshKey
    {
        public long HmiRefreshKeyId { get; set; }
        public long FKEventId { get; set; }
        public string HmiRefreshKey1 { get; set; }
    }
}
