//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L2L3WorkOrderReport
    {
        public long Counter { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime UpdatedTs { get; set; }
        public short CommStatus { get; set; }
        public string WorkOrderName { get; set; }
        public string ProductName { get; set; }
        public short ProductsNumber { get; set; }
        public double TotalProductsWeight { get; set; }
        public double TotalRawMaterialWeight { get; set; }
        public short RawMaterialsPlanned { get; set; }
        public short RawMaterialsDischarged { get; set; }
        public short RawMaterialsRolled { get; set; }
        public short RawMaterialsScrapped { get; set; }
        public short RawMaterialsRejected { get; set; }
        public double MetallicYield { get; set; }
        public short EventType { get; set; }
        public Nullable<System.DateTime> ProductionStart { get; set; }
        public Nullable<System.DateTime> ProductionEnd { get; set; }
    }
}
