//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L3L2WorkOrderDefinition
    {
        public long CounterId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime UpdatedTs { get; set; }
        public Nullable<PE.DbEntity.Enums.CommStatus> CommStatus { get; set; }
        public string WorkOrderName { get; set; }
        public string ProductName { get; set; }
        public Nullable<System.DateTime> CreatedInL3 { get; set; }
        public Nullable<System.DateTime> ToBeCompletedBefore { get; set; }
        public string CustomerName { get; set; }
        public Nullable<double> TargetOrderWeight { get; set; }
        public Nullable<double> TargetOrderWeightMin { get; set; }
        public Nullable<double> TargetOrderWeightMax { get; set; }
        public string HeatName { get; set; }
        public Nullable<short> RawMaterialNumber { get; set; }
        public string RawMaterialShapeType { get; set; }
        public Nullable<double> RawMaterialThickness { get; set; }
        public Nullable<double> RawMaterialWidth { get; set; }
        public Nullable<double> RawMaterialLength { get; set; }
        public Nullable<double> RawMaterialWeight { get; set; }
        public string SteelgradeCode { get; set; }
        public string ExternalSteelgradeCode { get; set; }
        public string RawMaterialType { get; set; }
        public string NextAggregate { get; set; }
        public string OperationCode { get; set; }
        public string ReheatingGroupName { get; set; }
        public string QualityPolicy { get; set; }
        public string ExtraLabelInformation { get; set; }
        public string ValidationCheck { get; set; }
        public string WorkOrderNameStatus { get; set; }
        public string CommMessage { get; set; }
    }
}
