//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNTEquipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MNTEquipment()
        {
            this.MNTEquipments1 = new HashSet<MNTEquipment>();
            this.MNTEquipmentHistories = new HashSet<MNTEquipmentHistory>();
        }
    
        public long EquipmentId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public string EquipmentCode { get; set; }
        public string EquipmentName { get; set; }
        public string EquipmentDescription { get; set; }
        public long FKEquipmentGroupId { get; set; }
        public Nullable<long> FKEquipmentSupplierId { get; set; }
        public Nullable<long> FKAssetId { get; set; }
        public Nullable<long> ParentEquipmentId { get; set; }
        public PE.DbEntity.Enums.EquipmentStatus EquipmentStatus { get; set; }
        public short AccumulationType { get; set; }
        public Nullable<long> ActualValue { get; set; }
        public Nullable<long> WarningValue { get; set; }
        public Nullable<long> AlarmValue { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> ServiceExpires { get; set; }
        public Nullable<long> CntMatsProcessed { get; set; }
    
        public virtual MNTEquipmentGroup MNTEquipmentGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MNTEquipment> MNTEquipments1 { get; set; }
        public virtual MNTEquipment MNTEquipment1 { get; set; }
        public virtual MVHAsset MVHAsset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MNTEquipmentHistory> MNTEquipmentHistories { get; set; }
    }
}
