//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNTEquipmentGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MNTEquipmentGroup()
        {
            this.MNTEquipmentGroups1 = new HashSet<MNTEquipmentGroup>();
            this.MNTEquipments = new HashSet<MNTEquipment>();
        }
    
        public long EquipmentGroupId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public string EquipmentGroupCode { get; set; }
        public string EquipmentGroupName { get; set; }
        public string EquipmentGroupDescription { get; set; }
        public Nullable<long> ParentEquipmentGroupId { get; set; }
        public bool IsDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MNTEquipmentGroup> MNTEquipmentGroups1 { get; set; }
        public virtual MNTEquipmentGroup MNTEquipmentGroup1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MNTEquipment> MNTEquipments { get; set; }
    }
}
