//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNTEquipmentHistory
    {
        public long EquipmentHistoryId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public long FKEquipmentId { get; set; }
        public Nullable<long> MaterialsProcessed { get; set; }
        public Nullable<double> WeightProcessed { get; set; }
        public PE.DbEntity.Enums.EquipmentStatus EquipmentStatus { get; set; }
        public string Remark { get; set; }
    
        public virtual MNTEquipment MNTEquipment { get; set; }
    }
}
