//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVHAssetsEXT
    {
        public long FKAssetId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public Nullable<short> TimeIn { get; set; }
        public short MaxPassNo { get; set; }
        public Nullable<bool> IsInitial { get; set; }
        public Nullable<PE.DbEntity.Enums.AssetsArea> EnumArea { get; set; }
        public Nullable<bool> IsLast { get; set; }
    
        public virtual MVHAsset MVHAsset { get; set; }
    }
}
