//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVHAsset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MVHAsset()
        {
            this.MVHAssets1 = new HashSet<MVHAsset>();
            this.MVHFeatures = new HashSet<MVHFeature>();
            this.MVHRawMaterialsSteps = new HashSet<MVHRawMaterialsStep>();
            this.MNTEquipments = new HashSet<MNTEquipment>();
        }
    
        public long AssetId { get; set; }
        public short OrderSeq { get; set; }
        public bool IsCheckpoint { get; set; }
        public bool IsReversible { get; set; }
        public string AssetCode { get; set; }
        public string AssetName { get; set; }
        public string AssetDescription { get; set; }
        public Nullable<long> ParentAssetId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHAsset> MVHAssets1 { get; set; }
        public virtual MVHAsset MVHAsset1 { get; set; }
        public virtual MVHAssetsEXT MVHAssetsEXT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHFeature> MVHFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHRawMaterialsStep> MVHRawMaterialsSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MNTEquipment> MNTEquipments { get; set; }
    }
}
