//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVHDefect
    {
        public long DefectId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public long FKDefectCatalogueId { get; set; }
        public Nullable<long> FKRawMaterialId { get; set; }
        public Nullable<long> FKProductId { get; set; }
        public string DefectName { get; set; }
        public Nullable<short> DefectPosition { get; set; }
        public Nullable<short> DefectFrequency { get; set; }
        public Nullable<short> DefectScale { get; set; }
        public string DefectDescription { get; set; }
    
        public virtual MVHDefectCatalogue MVHDefectCatalogue { get; set; }
        public virtual MVHRawMaterial MVHRawMaterial { get; set; }
        public virtual PRMProduct PRMProduct { get; set; }
    }
}
