//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVHDefectCatalogue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MVHDefectCatalogue()
        {
            this.MVHDefectCatalogue1 = new HashSet<MVHDefectCatalogue>();
            this.MVHDefects = new HashSet<MVHDefect>();
        }
    
        public long DefectCatalogueId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public string DefectCatalogueCode { get; set; }
        public string DefectCatalogueName { get; set; }
        public string DefectCatalogueDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsDefault { get; set; }
        public long FKDefectCatalogueCategoryId { get; set; }
        public Nullable<long> ParentDefectCatalogueId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHDefectCatalogue> MVHDefectCatalogue1 { get; set; }
        public virtual MVHDefectCatalogue MVHDefectCatalogue2 { get; set; }
        public virtual MVHDefectCatalogueCategory MVHDefectCatalogueCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHDefect> MVHDefects { get; set; }
    }
}
