//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVHFeature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MVHFeature()
        {
            this.MVHMeasurements = new HashSet<MVHMeasurement>();
            this.MVHRawMaterialsSteps = new HashSet<MVHRawMaterialsStep>();
            this.MVHTriggersFeatures = new HashSet<MVHTriggersFeature>();
        }
    
        public long FeatureId { get; set; }
        public long FKAssetId { get; set; }
        public long FKUnitOfMeasureId { get; set; }
        public long FKDataTypeId { get; set; }
        public bool IsActive { get; set; }
        public bool IsTrigger { get; set; }
        public bool IsMaterialRelated { get; set; }
        public bool IsLengthRelated { get; set; }
        public bool IsNewProcessingStep { get; set; }
        public int FeatureCode { get; set; }
        public string FeatureName { get; set; }
        public string FeatureDescription { get; set; }
        public PE.DbEntity.Enums.FeatureType EnumFeatureType { get; set; }
    
        public virtual DataType DataType { get; set; }
        public virtual MVHFeaturesEXT MVHFeaturesEXT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHMeasurement> MVHMeasurements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHRawMaterialsStep> MVHRawMaterialsSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHTriggersFeature> MVHTriggersFeatures { get; set; }
        public virtual MVHAsset MVHAsset { get; set; }
    }
}
