//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVHFeaturesEXT
    {
        public long FKFeatureId { get; set; }
        public Nullable<short> ResNum { get; set; }
        public Nullable<short> ResDen { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> MaxValue { get; set; }
        public string ListValues { get; set; }
        public bool IsSampled { get; set; }
        public Nullable<long> ExternalFKUnitOfMeasureId { get; set; }
        public Nullable<short> EnumTypeOfCut { get; set; }
        public bool IsLengthChange { get; set; }
        public bool IsPossibleInversion { get; set; }
        public Nullable<bool> IsWeightChange { get; set; }
        public Nullable<bool> OnAssetEntry { get; set; }
    
        public virtual MVHFeature MVHFeature { get; set; }
    }
}
