//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVHMeasurement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MVHMeasurement()
        {
            this.MVHSamples = new HashSet<MVHSample>();
        }
    
        public long MeasurementId { get; set; }
        public Nullable<long> FKRawMaterialId { get; set; }
        public long FKFeatureId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public short NoOfSamples { get; set; }
        public double ValueAvg { get; set; }
        public Nullable<double> ValueMin { get; set; }
        public Nullable<double> ValueMax { get; set; }
        public Nullable<System.DateTime> FirstMeasurement { get; set; }
        public Nullable<System.DateTime> LastMeasurement { get; set; }
        public bool IsValid { get; set; }
        public Nullable<double> ActualLength { get; set; }
        public short PassNo { get; set; }
        public bool IsLastPass { get; set; }
    
        public virtual MVHMeasurementsEXT MVHMeasurementsEXT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHSample> MVHSamples { get; set; }
        public virtual MVHRawMaterial MVHRawMaterial { get; set; }
        public virtual MVHFeature MVHFeature { get; set; }
    }
}
