//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVHQualityControlCatalogue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MVHQualityControlCatalogue()
        {
            this.MVHQualityControls = new HashSet<MVHQualityControl>();
        }
    
        public long QualityControlCatalogueId { get; set; }
        public string QualityControlCode { get; set; }
        public string QualityControlName { get; set; }
        public string QualityControlDescription { get; set; }
        public long FKUnitOfMeasureId { get; set; }
        public short QualityControlDescriptionMethod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHQualityControl> MVHQualityControls { get; set; }
    }
}
