//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVHQualityControl
    {
        public long QualityControlId { get; set; }
        public short Result { get; set; }
        public Nullable<double> MeasuredValue { get; set; }
        public string Comments { get; set; }
        public Nullable<long> FKRawMaterialId { get; set; }
        public Nullable<long> FKQualityControlCatalogueId { get; set; }
        public Nullable<long> FKProductId { get; set; }
    
        public virtual MVHRawMaterial MVHRawMaterial { get; set; }
        public virtual PRMProduct PRMProduct { get; set; }
        public virtual MVHQualityControlCatalogue MVHQualityControlCatalogue { get; set; }
    }
}
