//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVHRawMaterialsStep
    {
        public long RawMaterialStepId { get; set; }
        public long FKRawMaterialId { get; set; }
        public PE.DbEntity.Enums.RawMaterialStepNo ProcessingStepNo { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public bool IsReversed { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Thickness { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> HeadPartLength { get; set; }
        public Nullable<double> TailPartLength { get; set; }
        public Nullable<double> HeadPartCumm { get; set; }
        public Nullable<double> TailPartCumm { get; set; }
        public Nullable<double> Elongation { get; set; }
        public Nullable<double> MotherOffset { get; set; }
        public Nullable<double> RelLength { get; set; }
        public Nullable<long> FKAssetId { get; set; }
        public short PassNo { get; set; }
        public bool IsLastPass { get; set; }
        public Nullable<PE.DbEntity.Enums.TypeOfCut> EnumTypeOfCut { get; set; }
        public Nullable<long> FKFeatureIdRef { get; set; }
    
        public virtual MVHRawMaterialsStepsEXT MVHRawMaterialsStepsEXT { get; set; }
        public virtual MVHRawMaterial MVHRawMaterial { get; set; }
        public virtual MVHFeature MVHFeature { get; set; }
        public virtual MVHAsset MVHAsset { get; set; }
    }
}
