//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVHRawMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MVHRawMaterial()
        {
            this.DLSDelays = new HashSet<DLSDelay>();
            this.MVHMeasurements = new HashSet<MVHMeasurement>();
            this.MVHRawMaterialsSteps = new HashSet<MVHRawMaterialsStep>();
            this.MVHRawMaterials1 = new HashSet<MVHRawMaterial>();
            this.MVHQualityControls = new HashSet<MVHQualityControl>();
            this.MVHDefects = new HashSet<MVHDefect>();
        }
    
        public long RawMaterialId { get; set; }
        public string RawMaterialName { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public bool IsDummy { get; set; }
        public bool IsVirtual { get; set; }
        public PE.DbEntity.Enums.RawMaterialStatus Status { get; set; }
        public PE.DbEntity.Enums.RawMaterialStepNo LastProcessingStepNo { get; set; }
        public short CuttingSeqNo { get; set; }
        public short ChildsNo { get; set; }
        public Nullable<long> FKMaterialId { get; set; }
        public Nullable<long> FKProductId { get; set; }
        public Nullable<long> ParentRawMaterialId { get; set; }
        public long ExternalRawMaterialId { get; set; }
        public bool IsTransferred2DW { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DLSDelay> DLSDelays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHMeasurement> MVHMeasurements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHRawMaterialsStep> MVHRawMaterialsSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHRawMaterial> MVHRawMaterials1 { get; set; }
        public virtual MVHRawMaterial MVHRawMaterial1 { get; set; }
        public virtual MVHRawMaterialsEXT MVHRawMaterialsEXT { get; set; }
        public virtual PRMProduct PRMProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHQualityControl> MVHQualityControls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHDefect> MVHDefects { get; set; }
        public virtual PRMMaterial PRMMaterial { get; set; }
    }
}
