//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVHTrigger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MVHTrigger()
        {
            this.MVHTriggersFeatures = new HashSet<MVHTriggersFeature>();
        }
    
        public long TriggerId { get; set; }
        public string TriggerCode { get; set; }
        public string TriggerName { get; set; }
        public string TriggerDescription { get; set; }
        public bool IsActive { get; set; }
        public PE.DbEntity.Enums.TriggerType EnumTriggerType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHTriggersFeature> MVHTriggersFeatures { get; set; }
    }
}
