//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRMCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRMCustomer()
        {
            this.PRMWorkOrders = new HashSet<PRMWorkOrder>();
        }
    
        public long CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string DocPatternName { get; set; }
        public string Country { get; set; }
        public string LogoName { get; set; }
        public string SAPKey { get; set; }
        public bool IsActive { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual PRMCustomersEXT PRMCustomersEXT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMWorkOrder> PRMWorkOrders { get; set; }
    }
}
