//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRMHeatChemAnalysi
    {
        public long HeatChemAnalysisId { get; set; }
        public long FKHeatId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public Nullable<System.DateTime> SampleTaken { get; set; }
        public Nullable<short> Laboratory { get; set; }
        public Nullable<double> Fe { get; set; }
        public Nullable<double> C { get; set; }
        public Nullable<double> Mn { get; set; }
        public Nullable<double> Cr { get; set; }
        public Nullable<double> Mo { get; set; }
        public Nullable<double> V { get; set; }
        public Nullable<double> Ni { get; set; }
        public Nullable<double> Co { get; set; }
        public Nullable<double> Si { get; set; }
        public Nullable<double> P { get; set; }
        public Nullable<double> S { get; set; }
        public Nullable<double> Cu { get; set; }
        public Nullable<double> Nb { get; set; }
        public Nullable<double> Al { get; set; }
        public Nullable<double> N { get; set; }
        public Nullable<double> Ca { get; set; }
        public Nullable<double> B { get; set; }
        public Nullable<double> Ti { get; set; }
        public Nullable<double> Sn { get; set; }
        public Nullable<double> O { get; set; }
        public Nullable<double> H { get; set; }
        public Nullable<double> W { get; set; }
        public Nullable<double> Pb { get; set; }
        public Nullable<double> Zn { get; set; }
        public Nullable<double> As { get; set; }
        public Nullable<double> Mg { get; set; }
        public Nullable<double> Sb { get; set; }
        public Nullable<double> Bi { get; set; }
        public Nullable<double> Ta { get; set; }
        public Nullable<double> Zr { get; set; }
        public Nullable<double> Ce { get; set; }
        public Nullable<double> Te { get; set; }
    
        public virtual PRMHeat PRMHeat { get; set; }
    }
}
