//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRMHeat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRMHeat()
        {
            this.PRMHeatChemAnalysis = new HashSet<PRMHeatChemAnalysi>();
            this.PRMMaterials = new HashSet<PRMMaterial>();
        }
    
        public long HeatId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public string HeatName { get; set; }
        public long FKMaterialCatalogueId { get; set; }
        public Nullable<long> FKHeatSupplierId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<double> HeatWeightRef { get; set; }
        public Nullable<bool> IsDummy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMHeatChemAnalysi> PRMHeatChemAnalysis { get; set; }
        public virtual PRMHeatsEXT PRMHeatsEXT { get; set; }
        public virtual PRMHeatSupplier PRMHeatSupplier { get; set; }
        public virtual PRMMaterialCatalogue PRMMaterialCatalogue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMMaterial> PRMMaterials { get; set; }
    }
}
