//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRMMaterialCatalogue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRMMaterialCatalogue()
        {
            this.PRMWorkOrders = new HashSet<PRMWorkOrder>();
            this.PRMHeats = new HashSet<PRMHeat>();
        }
    
        public long MaterialCatalogueId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public bool IsActive { get; set; }
        public bool IsDefault { get; set; }
        public string MaterialCatalogueName { get; set; }
        public long FKMaterialCatalogueTypeId { get; set; }
        public long FKShapeId { get; set; }
        public string Description { get; set; }
        public string SAPNumber { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> LengthMin { get; set; }
        public Nullable<double> LengthMax { get; set; }
        public double Thickness { get; set; }
        public Nullable<double> ThicknessMin { get; set; }
        public Nullable<double> ThicknessMax { get; set; }
        public double Width { get; set; }
        public Nullable<double> WidthMin { get; set; }
        public Nullable<double> WidthMax { get; set; }
        public double Weight { get; set; }
        public Nullable<double> WeightMin { get; set; }
        public Nullable<double> WeightMax { get; set; }
        public long FKSteelgradeId { get; set; }
    
        public virtual PRMMaterialCatalogueType PRMMaterialCatalogueType { get; set; }
        public virtual PRMShape PRMShape { get; set; }
        public virtual PRMMaterialCatalogueEXT PRMMaterialCatalogueEXT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMWorkOrder> PRMWorkOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMHeat> PRMHeats { get; set; }
        public virtual PRMSteelgrade PRMSteelgrade { get; set; }
    }
}
