//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRMMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRMMaterial()
        {
            this.MVHRawMaterials = new HashSet<MVHRawMaterial>();
        }
    
        public long MaterialId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public bool IsDummy { get; set; }
        public string MaterialName { get; set; }
        public double Weight { get; set; }
        public bool IsAssigned { get; set; }
        public long FKHeatId { get; set; }
        public long FKWorkOrderId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHRawMaterial> MVHRawMaterials { get; set; }
        public virtual PRMMaterialsEXT PRMMaterialsEXT { get; set; }
        public virtual PRMHeat PRMHeat { get; set; }
        public virtual PRMWorkOrder PRMWorkOrder { get; set; }
    }
}
