//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRMProductCatalogue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRMProductCatalogue()
        {
            this.PRMWorkOrders = new HashSet<PRMWorkOrder>();
        }
    
        public long ProductCatalogueId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public bool IsActive { get; set; }
        public bool IsDefault { get; set; }
        public string ProductCatalogueName { get; set; }
        public long FKProductCatalogueTypeId { get; set; }
        public long FKShapeId { get; set; }
        public string Description { get; set; }
        public string SAPNumber { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> LengthMin { get; set; }
        public Nullable<double> LengthMax { get; set; }
        public Nullable<double> Thickness { get; set; }
        public Nullable<double> ThicknessMin { get; set; }
        public Nullable<double> ThicknessMax { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> WidthMin { get; set; }
        public Nullable<double> WidthMax { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> WeightMin { get; set; }
        public Nullable<double> WeightMax { get; set; }
        public bool Slitting { get; set; }
        public double ExitSpeed { get; set; }
        public double StdMetallicYield { get; set; }
        public double StdQualityYield { get; set; }
        public double StdGapTime { get; set; }
        public double StdRollingTime { get; set; }
        public double StdUtilizationTime { get; set; }
        public Nullable<double> StdProductionTime { get; set; }
        public Nullable<double> MaxTensile { get; set; }
        public Nullable<double> MaxYieldPoint { get; set; }
        public Nullable<double> Ovality { get; set; }
        public Nullable<double> MaxOvality { get; set; }
        public Nullable<double> ProfileToleranceMin { get; set; }
        public Nullable<double> ProfileToleranceMax { get; set; }
        public double StdProductivity { get; set; }
        public long FKSteelgradeId { get; set; }
    
        public virtual PRMShape PRMShape { get; set; }
        public virtual PRMProductCatalogueEXT PRMProductCatalogueEXT { get; set; }
        public virtual PRMProductCatalogueType PRMProductCatalogueType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMWorkOrder> PRMWorkOrders { get; set; }
        public virtual PRMSteelgrade PRMSteelgrade { get; set; }
    }
}
