//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRMProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRMProduct()
        {
            this.MVHRawMaterials = new HashSet<MVHRawMaterial>();
            this.MVHDefects = new HashSet<MVHDefect>();
            this.MVHQualityControls = new HashSet<MVHQualityControl>();
        }
    
        public long ProductId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public bool IsDummy { get; set; }
        public string ProductName { get; set; }
        public Nullable<long> FKWorkOrderId { get; set; }
        public double Weight { get; set; }
        public bool IsAssigned { get; set; }
        public PE.DbEntity.Enums.ProductQuality QualityEnum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHRawMaterial> MVHRawMaterials { get; set; }
        public virtual PRMProductsEXT PRMProductsEXT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHDefect> MVHDefects { get; set; }
        public virtual PRMWorkOrder PRMWorkOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVHQualityControl> MVHQualityControls { get; set; }
    }
}
