//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRMProductCatalogueType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRMProductCatalogueType()
        {
            this.PRMProductCatalogues = new HashSet<PRMProductCatalogue>();
        }
    
        public long ProductCatalogueTypeId { get; set; }
        public string ProductCatalogueTypeSymbol { get; set; }
        public string ProductCatalogueTypeName { get; set; }
        public string ProductCatalogueTypeDescription { get; set; }
        public bool IsDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMProductCatalogue> PRMProductCatalogues { get; set; }
    }
}
