//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRMReheatingGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRMReheatingGroup()
        {
            this.PRMWorkOrders = new HashSet<PRMWorkOrder>();
        }
    
        public long ReheatingGroupId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public string ReheatingGroupName { get; set; }
        public Nullable<double> Zone1HeatingTime { get; set; }
        public Nullable<double> Zone2HeatingTime { get; set; }
        public Nullable<double> Zone3HeatingTime { get; set; }
        public Nullable<double> Zone4HeatingTime { get; set; }
        public Nullable<double> Zone5HeatingTime { get; set; }
        public Nullable<double> Zone6HeatingTime { get; set; }
        public Nullable<double> Zone7HeatingTime { get; set; }
        public Nullable<double> TotalHeatingTime { get; set; }
        public Nullable<double> UsedTime { get; set; }
        public Nullable<double> MaxHeatingTime { get; set; }
        public Nullable<double> Zone1HeatingTempMin { get; set; }
        public Nullable<double> Zone2HeatingTempMin { get; set; }
        public Nullable<double> Zone3HeatingTempMin { get; set; }
        public Nullable<double> Zone4HeatingTempMin { get; set; }
        public Nullable<double> Zone5HeatingTempMin { get; set; }
        public Nullable<double> Zone6HeatingTempMin { get; set; }
        public Nullable<double> Zone7HeatingTempMin { get; set; }
        public Nullable<double> Zone1HeatingTempMax { get; set; }
        public Nullable<double> Zone2HeatingTempMax { get; set; }
        public Nullable<double> Zone3HeatingTempMax { get; set; }
        public Nullable<double> Zone4HeatingTempMax { get; set; }
        public Nullable<double> Zone5HeatingTempMax { get; set; }
        public Nullable<double> Zone6HeatingTempMax { get; set; }
        public Nullable<double> Zone7HeatingTempMax { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string ReheatingGroupCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMWorkOrder> PRMWorkOrders { get; set; }
    }
}
