//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRMSteelgrade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRMSteelgrade()
        {
            this.PRMMaterialCatalogues = new HashSet<PRMMaterialCatalogue>();
            this.PRMProductCatalogues = new HashSet<PRMProductCatalogue>();
            this.PRMSteelgrades1 = new HashSet<PRMSteelgrade>();
        }
    
        public long SteelgradeId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public bool IsDefault { get; set; }
        public string SteelgradeCode { get; set; }
        public string SteelgradeName { get; set; }
        public string SteelgradeDescription { get; set; }
        public Nullable<double> Density { get; set; }
        public Nullable<double> OvenRecipeTemperature { get; set; }
        public string QualitySpecification { get; set; }
        public string CommercialGroup { get; set; }
        public string CustomerUseCode { get; set; }
        public string CustomerUseDescription { get; set; }
        public Nullable<long> FKSteelGroupId { get; set; }
        public Nullable<long> ParentSteelgradeId { get; set; }
    
        public virtual PRMSteelgradeChemicalComposition PRMSteelgradeChemicalComposition { get; set; }
        public virtual PRMSteelgradesEXT PRMSteelgradesEXT { get; set; }
        public virtual PRMSteelGroup PRMSteelGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMMaterialCatalogue> PRMMaterialCatalogues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMProductCatalogue> PRMProductCatalogues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMSteelgrade> PRMSteelgrades1 { get; set; }
        public virtual PRMSteelgrade PRMSteelgrade1 { get; set; }
    }
}
