//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRMSteelGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRMSteelGroup()
        {
            this.PRMSteelGroups1 = new HashSet<PRMSteelGroup>();
            this.PRMSteelgrades = new HashSet<PRMSteelgrade>();
        }
    
        public long SteelGroupId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public string SteelGroupName { get; set; }
        public Nullable<long> ParentSteelGroupId { get; set; }
        public bool IsDefault { get; set; }
        public string SteelGroupCode { get; set; }
        public string SteelGroupDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMSteelGroup> PRMSteelGroups1 { get; set; }
        public virtual PRMSteelGroup PRMSteelGroup1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMSteelgrade> PRMSteelgrades { get; set; }
    }
}
