//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRMShape
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRMShape()
        {
            this.PRMMaterialCatalogues = new HashSet<PRMMaterialCatalogue>();
            this.PRMProductCatalogues = new HashSet<PRMProductCatalogue>();
        }
    
        public long ShapeId { get; set; }
        public string ShapeSymbol { get; set; }
        public string ShapeName { get; set; }
        public string ShapeDescription { get; set; }
        public bool IsDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMMaterialCatalogue> PRMMaterialCatalogues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMProductCatalogue> PRMProductCatalogues { get; set; }
    }
}
