//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRMWorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRMWorkOrder()
        {
            this.PPLSchedules = new HashSet<PPLSchedule>();
            this.PRMProducts = new HashSet<PRMProduct>();
            this.PRMMaterials = new HashSet<PRMMaterial>();
        }
    
        public long WorkOrderId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public PE.DbEntity.Enums.OrderStatus WorkOrderStatus { get; set; }
        public string WorkOrderName { get; set; }
        public long FKProductCatalogueId { get; set; }
        public long FKMaterialCatalogueId { get; set; }
        public bool IsTestOrder { get; set; }
        public double TargetOrderWeight { get; set; }
        public Nullable<double> TargetOrderWeightMin { get; set; }
        public Nullable<double> TargetOrderWeightMax { get; set; }
        public System.DateTime CreatedInL3 { get; set; }
        public System.DateTime ToBeCompletedBefore { get; set; }
        public Nullable<long> FKCustomerId { get; set; }
        public Nullable<long> FKReheatingGroupId { get; set; }
        public string NextAggregate { get; set; }
        public string OperationCode { get; set; }
        public string QualityPolicy { get; set; }
        public string ExtraLabelInformation { get; set; }
        public string ExternalSteelgradeCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPLSchedule> PPLSchedules { get; set; }
        public virtual PRMCustomer PRMCustomer { get; set; }
        public virtual PRMMaterialCatalogue PRMMaterialCatalogue { get; set; }
        public virtual PRMProductCatalogue PRMProductCatalogue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMProduct> PRMProducts { get; set; }
        public virtual PRMReheatingGroup PRMReheatingGroup { get; set; }
        public virtual PRMWorkOrdersEXT PRMWorkOrdersEXT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMMaterial> PRMMaterials { get; set; }
    }
}
