//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RLSCassette
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RLSCassette()
        {
            this.RLSRollSetHistories = new HashSet<RLSRollSetHistory>();
        }
    
        public long CassetteId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public long FKCassetteTypeId { get; set; }
        public Nullable<long> FKStandId { get; set; }
        public string CassetteName { get; set; }
        public string CassetteDescription { get; set; }
        public PE.DbEntity.Enums.CassetteStatus Status { get; set; }
        public short NumberOfPositions { get; set; }
        public PE.DbEntity.Enums.CassetteArrangement Arrangement { get; set; }
    
        public virtual RLSCassetteType RLSCassetteType { get; set; }
        public virtual RLSStand RLSStand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RLSRollSetHistory> RLSRollSetHistories { get; set; }
    }
}
