//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RLSGrooveTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RLSGrooveTemplate()
        {
            this.RLSRollGroovesHistories = new HashSet<RLSRollGroovesHistory>();
        }
    
        public long GrooveTemplateId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public string Shape { get; set; }
        public string GrooveTemplateCode { get; set; }
        public string GrooveTemplateName { get; set; }
        public string GrooveTemplateDescription { get; set; }
        public string GrindingProgramName { get; set; }
        public short Status { get; set; }
        public Nullable<double> R1 { get; set; }
        public Nullable<double> R2 { get; set; }
        public Nullable<double> R3 { get; set; }
        public Nullable<double> D1 { get; set; }
        public Nullable<double> D2 { get; set; }
        public Nullable<double> W1 { get; set; }
        public Nullable<double> W2 { get; set; }
        public Nullable<double> Angle1 { get; set; }
        public Nullable<double> Angle2 { get; set; }
        public Nullable<double> Ds { get; set; }
        public Nullable<double> Dw { get; set; }
        public Nullable<double> SpreadFactor { get; set; }
        public Nullable<double> Plane { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RLSRollGroovesHistory> RLSRollGroovesHistories { get; set; }
    }
}
