//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RLSRollSetHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RLSRollSetHistory()
        {
            this.RLSRollGroovesHistories = new HashSet<RLSRollGroovesHistory>();
        }
    
        public long RollSetHistoryId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public long FKRollSetId { get; set; }
        public Nullable<long> FKCassetteId { get; set; }
        public Nullable<System.DateTime> Mounted { get; set; }
        public Nullable<System.DateTime> Dismounted { get; set; }
        public PE.DbEntity.Enums.RollSetHistoryStatus Status { get; set; }
        public Nullable<short> PositionInCassette { get; set; }
        public Nullable<double> AccWeightLimit { get; set; }
    
        public virtual RLSCassette RLSCassette { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RLSRollGroovesHistory> RLSRollGroovesHistories { get; set; }
        public virtual RLSRollSet RLSRollSet { get; set; }
    }
}
