//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RLSRollSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RLSRollSet()
        {
            this.RLSRollSetHistories = new HashSet<RLSRollSetHistory>();
        }
    
        public long RollSetId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public Nullable<long> FKUpperRollId { get; set; }
        public Nullable<long> FKBottomRollId { get; set; }
        public Nullable<long> FKThirdRollId { get; set; }
        public PE.DbEntity.Enums.RollSetStatus Status { get; set; }
        public PE.DbEntity.Enums.RollSetType RollSetType { get; set; }
        public System.DateTime Created { get; set; }
        public string RollSetName { get; set; }
        public string RollSetDescription { get; set; }
        public Nullable<short> IsThirdRoll { get; set; }
    
        public virtual RLSRoll RLSRoll { get; set; }
        public virtual RLSRoll RLSRoll1 { get; set; }
        public virtual RLSRoll RLSRoll2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RLSRollSetHistory> RLSRollSetHistories { get; set; }
    }
}
