//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RLSRollType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RLSRollType()
        {
            this.RLSRolls = new HashSet<RLSRoll>();
        }
    
        public long RollTypeId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public string RollTypeName { get; set; }
        public string RollTypeDescription { get; set; }
        public Nullable<double> DiameterMin { get; set; }
        public Nullable<double> DiameterMax { get; set; }
        public Nullable<double> RoughnessMin { get; set; }
        public Nullable<double> RoughnessMax { get; set; }
        public Nullable<double> YieldStrengthRef { get; set; }
        public string SteelgradeRoll { get; set; }
        public Nullable<double> Length { get; set; }
        public string DrawingName { get; set; }
        public string ChokeType { get; set; }
        public Nullable<long> AccBilletCntLimit { get; set; }
        public Nullable<double> AccWeightLimit { get; set; }
        public Nullable<short> MatchingRollsetType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RLSRoll> RLSRolls { get; set; }
    }
}
