//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RLSRoll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RLSRoll()
        {
            this.RLSRollGroovesHistories = new HashSet<RLSRollGroovesHistory>();
            this.RLSRollSets = new HashSet<RLSRollSet>();
            this.RLSRollSets1 = new HashSet<RLSRollSet>();
            this.RLSRollSets2 = new HashSet<RLSRollSet>();
        }
    
        public long RollId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public long FKRollTypeId { get; set; }
        public string RollName { get; set; }
        public string RollDescription { get; set; }
        public PE.DbEntity.Enums.RollStatus Status { get; set; }
        public double InitialDiameter { get; set; }
        public double ActualDiameter { get; set; }
        public Nullable<double> MinimumDiameter { get; set; }
        public Nullable<short> Location { get; set; }
        public short GroovesNumber { get; set; }
        public string Supplier { get; set; }
        public Nullable<PE.DbEntity.Enums.RollScrapReason> ScrapReason { get; set; }
        public Nullable<System.DateTime> ScrapDate { get; set; }
        public Nullable<short> RollType { get; set; }
        public Nullable<double> DiameterOfMaterial { get; set; }
        public Nullable<double> DiameterOfTool { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RLSRollGroovesHistory> RLSRollGroovesHistories { get; set; }
        public virtual RLSRollType RLSRollType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RLSRollSet> RLSRollSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RLSRollSet> RLSRollSets1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RLSRollSet> RLSRollSets2 { get; set; }
    }
}
