//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftCalendar
    {
        public long ShiftCalendarId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public long FKShiftDefinitionId { get; set; }
        public long FKCrewId { get; set; }
        public long FKDaysOfYear { get; set; }
        public System.DateTime PlannedStartTime { get; set; }
        public System.DateTime PlannedEndTime { get; set; }
        public bool IsActualShift { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual ShiftDefinition ShiftDefinition { get; set; }
        public virtual DaysOfYear DaysOfYear { get; set; }
        public virtual Crew Crew { get; set; }
    }
}
