//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STPTelegramValue
    {
        public long TelegramValueId { get; set; }
        public long FKTelegramId { get; set; }
        public string FKTelegramStructureIndex { get; set; }
        public string Value { get; set; }
    
        public virtual STPTelegram STPTelegram { get; set; }
    }
}
