//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STPTelegramStructure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STPTelegramStructure()
        {
            this.STPTelegrams = new HashSet<STPTelegram>();
        }
    
        public long TelegramStructureId { get; set; }
        public long FKTelegramElementId { get; set; }
        public Nullable<long> FKParentTelegramElementId { get; set; }
        public short SeqNo { get; set; }
        public string StructureCode { get; set; }
        public string StructureName { get; set; }
        public string StructureDescription { get; set; }
        public string StructureSource { get; set; }
        public string Prefix { get; set; }
        public string Sufix { get; set; }
        public bool IsActive { get; set; }
        public bool IsVisible { get; set; }
        public Nullable<bool> IsRoot { get; set; }
        public bool IsHeader { get; set; }
    
        public virtual STPTelegramElement STPTelegramElement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STPTelegram> STPTelegrams { get; set; }
        public virtual STPTelegramElement STPTelegramElement1 { get; set; }
    }
}
