//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STPTelegramElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STPTelegramElement()
        {
            this.STPTelegramStructures = new HashSet<STPTelegramStructure>();
            this.STPTelegramStructures1 = new HashSet<STPTelegramStructure>();
        }
    
        public long TelegramElementId { get; set; }
        public long FKDataTypeId { get; set; }
        public Nullable<long> FKUnitId { get; set; }
        public Nullable<short> ByteLength { get; set; }
        public string ElementCode { get; set; }
        public string ElementName { get; set; }
        public string ElementDescription { get; set; }
        public bool IsActive { get; set; }
        public bool IsVisible { get; set; }
        public bool IsStructure { get; set; }
    
        public virtual DataType DataType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STPTelegramStructure> STPTelegramStructures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STPTelegramStructure> STPTelegramStructures1 { get; set; }
    }
}
