//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CassettesOverview
    {
        public long CassetteId { get; set; }
        public string CassetteName { get; set; }
        public short Status { get; set; }
        public long FKCassetteTypeId { get; set; }
        public string CassetteTypeName { get; set; }
        public short NumberOfPositions { get; set; }
        public Nullable<long> StandId { get; set; }
        public Nullable<short> StandNo { get; set; }
        public short Arrangement { get; set; }
        public Nullable<int> RollsetsCnt { get; set; }
        public Nullable<short> NumberOfRolls { get; set; }
        public bool IsInterCassette { get; set; }
        public Nullable<short> Type { get; set; }
    }
}
