//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DefectsSummary
    {
        public long DefectId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public long FKDefectCatalogueId { get; set; }
        public Nullable<long> FKRawMaterialId { get; set; }
        public Nullable<long> FKProductId { get; set; }
        public string DefectName { get; set; }
        public Nullable<short> DefectPosition { get; set; }
        public Nullable<short> DefectFrequency { get; set; }
        public Nullable<short> DefectScale { get; set; }
        public string DefectDescription { get; set; }
        public string DefectCatalogueName { get; set; }
        public string DefectCatalogueCategoryName { get; set; }
        public Nullable<bool> IsRawMaterialRelated { get; set; }
        public Nullable<bool> IsProductRelated { get; set; }
        public string RawMaterialName { get; set; }
        public string ProductName { get; set; }
        public string DefectCatalogueCode { get; set; }
        public string DefectCatalogueCategoryCode { get; set; }
    }
}
