//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DelayOverview
    {
        public long Sorting { get; set; }
        public string DelayHeader { get; set; }
        public long DelayId { get; set; }
        public Nullable<System.DateTime> DateDay { get; set; }
        public Nullable<int> ShiftIdDelayStart { get; set; }
        public Nullable<int> ShiftIdDelayEnd { get; set; }
        public string ShiftCode { get; set; }
        public string DelayCatalogueCode { get; set; }
        public string DelayCatalogueName { get; set; }
        public string DelayCatalogueCategoryCode { get; set; }
        public string DelayCatalogueCategoryName { get; set; }
        public double StdDelayTime { get; set; }
        public System.DateTime DelayStart { get; set; }
        public Nullable<System.DateTime> DelayEnd { get; set; }
        public Nullable<double> DelayDuration { get; set; }
        public string DelayDurationFD { get; set; }
        public bool IsPlanned { get; set; }
        public int IsOpen { get; set; }
        public Nullable<long> WorkOrderId { get; set; }
        public string WorkOrderName { get; set; }
        public Nullable<long> RawMaterialId { get; set; }
        public string RawMaterialName { get; set; }
        public string FKUserId { get; set; }
        public string UserName { get; set; }
        public string UserComment { get; set; }
    }
}
