//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Events
    {
        public System.DateTime DateDay { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Quarter { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> DayNumber { get; set; }
        public Nullable<int> WeekDayNumber { get; set; }
        public Nullable<int> WeekNumber { get; set; }
        public long EventTypeId { get; set; }
        public string EventTypeName { get; set; }
        public System.DateTime EventTimeFrom { get; set; }
        public Nullable<System.DateTime> EventTimeTo { get; set; }
        public string EventName { get; set; }
        public string EventDescription { get; set; }
        public Nullable<long> EventAssetId { get; set; }
        public Nullable<long> EventMaterialId { get; set; }
        public string EventIndex { get; set; }
        public long EventInternalId { get; set; }
        public Nullable<long> ColorCheck { get; set; }
        public Nullable<long> ShiftCalendarId { get; set; }
        public long Sorting { get; set; }
    }
}
