//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FeaturesMap
    {
        public long SeqNo { get; set; }
        public Nullable<long> AssetSeq { get; set; }
        public long AssetId { get; set; }
        public string AssetCode { get; set; }
        public string AssetName { get; set; }
        public bool IsCheckpoint { get; set; }
        public Nullable<bool> IsInitial { get; set; }
        public Nullable<bool> IsLast { get; set; }
        public short MaxPassNo { get; set; }
        public Nullable<short> TimeIn { get; set; }
        public Nullable<short> EnumArea { get; set; }
        public long FeatureId { get; set; }
        public int FeatureCode { get; set; }
        public string FeatureName { get; set; }
        public bool IsNewProcessingStep { get; set; }
        public bool IsMaterialRelated { get; set; }
        public bool IsLengthRelated { get; set; }
        public bool IsActive { get; set; }
        public bool IsTrigger { get; set; }
        public short EnumFeatureType { get; set; }
        public string FeatureType { get; set; }
        public string UnitSymbol { get; set; }
        public string DataTypeName { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> MaxValue { get; set; }
        public string ListValues { get; set; }
        public Nullable<bool> OnAssetEntry { get; set; }
        public bool IsLengthChange { get; set; }
        public Nullable<bool> IsWeightChange { get; set; }
        public bool IsPossibleInversion { get; set; }
        public long UnitId { get; set; }
        public string UnintCategoryName { get; set; }
    }
}
