//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GroovesView4Accumulation
    {
        public long FKRollSetId { get; set; }
        public long RollSetHistoryId { get; set; }
        public Nullable<System.DateTime> Mounted { get; set; }
        public short RollSetHistoryStatus { get; set; }
        public Nullable<short> PositionInCassette { get; set; }
        public long RollGroovesHistoryId { get; set; }
        public short GrooveNumber { get; set; }
        public long FKGrooveTemplateId { get; set; }
        public short GrooveStatus { get; set; }
        public long AccBilletCnt { get; set; }
        public double AccWeight { get; set; }
        public Nullable<double> ActDiameter { get; set; }
        public long FKCassetteTypeId { get; set; }
        public string CassetteName { get; set; }
        public short Arrangement { get; set; }
        public short StandNo { get; set; }
        public short StandStatus { get; set; }
        public long StandId { get; set; }
        public Nullable<short> NumberOfRolls { get; set; }
        public short RollSetStatus { get; set; }
        public Nullable<short> IsThirdRoll { get; set; }
    }
}
