//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Heats
    {
        public long HeatId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public string HeatName { get; set; }
        public long FKMaterialCatalogueId { get; set; }
        public Nullable<long> FKHeatSupplierId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<double> HeatWeightRef { get; set; }
        public Nullable<bool> IsDummy { get; set; }
        public string SteelgradeCode { get; set; }
        public string SteelgradeName { get; set; }
        public Nullable<double> Density { get; set; }
        public string MaterialCatalogueName { get; set; }
        public string SupplierName { get; set; }
    }
}
