//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_L3L1MaterialAssignment
    {
        public long Sorting { get; set; }
        public long RawMaterialId { get; set; }
        public string RawMaterialName { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public short Status { get; set; }
        public Nullable<long> MaterialId { get; set; }
        public string MaterialName { get; set; }
    }
}
