//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_L3L2TransferTablesSummary
    {
        public string TransferTableName { get; set; }
        public Nullable<int> StatusNew { get; set; }
        public Nullable<int> StatusInProc { get; set; }
        public Nullable<int> StatusOK { get; set; }
        public Nullable<int> StatusValErr { get; set; }
        public Nullable<int> StatusProcErr { get; set; }
        public long Sorting { get; set; }
    }
}
