//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Limits
    {
        public long LimitId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> UpperValueFloat { get; set; }
        public Nullable<double> LowerValueFloat { get; set; }
        public Nullable<long> UnitId { get; set; }
        public Nullable<int> UpperValueInt { get; set; }
        public Nullable<int> LowerValueInt { get; set; }
        public Nullable<System.DateTime> UpperValueDate { get; set; }
        public Nullable<System.DateTime> LowerValueDate { get; set; }
        public int ValueType { get; set; }
        public string ValueTypeName { get; set; }
        public long LimitGroupId { get; set; }
        public string LimitGroupName { get; set; }
        public string LimitGroupDescription { get; set; }
    }
}
