//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MaterialsInFurnace
    {
        public long Sorting { get; set; }
        public long RawMaterialId { get; set; }
        public int ExternalRawMaterialId { get; set; }
        public string RawMaterialName { get; set; }
        public short Status { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public long AssetId { get; set; }
        public string AssetName { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<long> L3MaterialId { get; set; }
        public string MaterialName { get; set; }
        public string WorkOrderName { get; set; }
        public string HeatName { get; set; }
        public string SteelgradeCode { get; set; }
        public Nullable<long> WorkOrderId { get; set; }
        public Nullable<long> HeatId { get; set; }
        public Nullable<long> SteelgradeId { get; set; }
        public int IsLastOne { get; set; }
        public int IsFirstOne { get; set; }
    }
}
