//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_NewestAlarmsList
    {
        public long AlarmId { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public System.DateTime AlarmDate { get; set; }
        public string AlarmOwner { get; set; }
        public string ShortDescription { get; set; }
        public long AlarmDefinitionId { get; set; }
        public Nullable<bool> Confirmation { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public short DisplayFlag { get; set; }
        public string AlarmCode { get; set; }
        public string Message { get; set; }
        public string AlarmCategoryName { get; set; }
        public int AlarmType { get; set; }
        public string LanguageCode { get; set; }
        public bool ToConfirm { get; set; }
        public bool ShowPopup { get; set; }
        public long RowNumber { get; set; }
    }
}
