//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PassChangeDataActual
    {
        public long RollSetHistoryId { get; set; }
        public Nullable<System.DateTime> Mounted { get; set; }
        public short Status { get; set; }
        public Nullable<short> PositionInCassette { get; set; }
        public long RollSetId { get; set; }
        public string RollSetName { get; set; }
        public short RollSetType { get; set; }
        public long CassetteId { get; set; }
        public string CassetteName { get; set; }
        public short Arrangement { get; set; }
        public long StandId { get; set; }
        public short StandNo { get; set; }
        public Nullable<short> Position { get; set; }
        public short StandStatus { get; set; }
        public double ActualDiameter { get; set; }
        public string RollTypeName { get; set; }
        public Nullable<long> AccBilletCntLimit { get; set; }
        public Nullable<double> AccWeightLimit { get; set; }
        public double AccWeight { get; set; }
        public long AccBilletCnt { get; set; }
        public short GrooveNumber { get; set; }
        public short GrooveStatus { get; set; }
        public long GrooveTemplateId { get; set; }
        public string GrooveTemplateName { get; set; }
    }
}
