//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ProductionHistory
    {
        public long ProductId { get; set; }
        public System.DateTime ProductCreated { get; set; }
        public string ProductName { get; set; }
        public double Weight { get; set; }
        public short QualityEnum { get; set; }
        public long WorkOrderId { get; set; }
        public string WorkOrderName { get; set; }
        public short WorkOrderStatus { get; set; }
        public long ProductCatalogueId { get; set; }
        public string ProductCatalogueName { get; set; }
        public long FKShapeId { get; set; }
        public string ShapeSymbol { get; set; }
        public string ShapeName { get; set; }
        public Nullable<double> Thickness { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> ProdCatRefWeight { get; set; }
        public long SteelgradeId { get; set; }
        public string SteelgradeCode { get; set; }
        public string SteelgradeName { get; set; }
        public long HeatId { get; set; }
        public string HeatName { get; set; }
        public Nullable<int> NumDefects { get; set; }
        public long ProductCatalogueTypeId { get; set; }
        public string ProductCatalogueTypeSymbol { get; set; }
        public string ProductCatalogueTypeName { get; set; }
    }
}
