//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Products
    {
        public long ProductId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public System.DateTime LastUpdateTs { get; set; }
        public bool IsDummy { get; set; }
        public string ProductName { get; set; }
        public Nullable<long> FKWorkOrderId { get; set; }
        public bool IsAssigned { get; set; }
        public double Weight { get; set; }
        public string WorkOrderName { get; set; }
        public Nullable<long> ShiftCalendarId { get; set; }
        public string ShiftKey { get; set; }
        public string NewColumn { get; set; }
    }
}
