//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RawMaterialOverview
    {
        public Nullable<long> Sorting { get; set; }
        public Nullable<short> Area { get; set; }
        public string AssetName { get; set; }
        public string ParentAssetName { get; set; }
        public System.DateTime RawMaterialCreated { get; set; }
        public System.DateTime RawMaterialLastUpdated { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public short RawMaterialStatus { get; set; }
        public long RawMaterialId { get; set; }
        public long RawMaterialExternalId { get; set; }
        public string RawMaterialName { get; set; }
        public Nullable<double> RawMaterialDeclaredWeight { get; set; }
        public Nullable<double> RawMaterialDeclaredLength { get; set; }
        public Nullable<double> RawMaterialInitialWeight { get; set; }
        public Nullable<double> RawMaterialInitialLength { get; set; }
        public Nullable<double> RawMaterialLastWeight { get; set; }
        public Nullable<double> RawMaterialLastLength { get; set; }
        public short LastStepNo { get; set; }
        public bool RawMaterialIsVirtual { get; set; }
        public Nullable<bool> IsMaterialAssigned { get; set; }
        public Nullable<bool> IsProductAssigned { get; set; }
        public string MaterialName { get; set; }
        public string HeatName { get; set; }
        public string SteelgradeCode { get; set; }
        public string SteelgradeName { get; set; }
        public string SteelGroupCode { get; set; }
        public string SteelGroupName { get; set; }
        public string WorkOrderName { get; set; }
        public string MaterialCatalogueName { get; set; }
        public string ProductCatalogueName { get; set; }
        public string ShiftKey { get; set; }
        public string ShiftCode { get; set; }
        public string CrewName { get; set; }
        public short RawMaterialCutNo { get; set; }
        public short RawMaterialChildNo { get; set; }
        public string ParentRawMaterialName { get; set; }
        public Nullable<long> ParentRawMaterialExternalId { get; set; }
        public Nullable<short> ParentRawMaterialCutNo { get; set; }
        public Nullable<short> ParentRawMaterialChildNo { get; set; }
        public bool RawMaterialInDW { get; set; }
        public Nullable<long> DimShiftKey { get; set; }
        public Nullable<long> DimWorkOrderKey { get; set; }
        public long DimRawMaterialKey { get; set; }
        public Nullable<long> DimMaterialKey { get; set; }
        public Nullable<long> DimProductKey { get; set; }
        public Nullable<long> DimSteelGroupKey { get; set; }
        public Nullable<long> DimSteelgradeKey { get; set; }
        public Nullable<long> DimHeatKey { get; set; }
        public short DimRawMaterialStatusKey { get; set; }
        public Nullable<long> DimParentRawMaterialKey { get; set; }
        public Nullable<short> DimParentRawMaterialStatusKey { get; set; }
        public Nullable<long> DimLastAssetKey { get; set; }
        public Nullable<long> DimCrewKey { get; set; }
        public Nullable<long> DimMaterialCatalogueKey { get; set; }
        public Nullable<long> DimProductCatalogueKey { get; set; }
        public Nullable<double> Asset29Weight { get; set; }
    }
}
