//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RawMaterialHistory
    {
        public long Sorting { get; set; }
        public long RawMaterialId { get; set; }
        public long RawMaterialStepId { get; set; }
        public System.DateTime CreatedTs { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<long> AssetId { get; set; }
        public short RawMaterialStep { get; set; }
        public short RawMaterialPassNo { get; set; }
        public bool RawMaterialIsLastPass { get; set; }
        public bool RawMaterialIsReversed { get; set; }
        public Nullable<double> RawMaterialThickness { get; set; }
        public Nullable<double> RawMaterialWeight { get; set; }
        public Nullable<double> RawMaterialLength { get; set; }
        public Nullable<double> RawMaterialDeclaredWeight { get; set; }
        public Nullable<double> RawMaterialDeclaredLength { get; set; }
        public Nullable<double> RawMaterialLastWeight { get; set; }
        public Nullable<double> RawMaterialLastLength { get; set; }
        public Nullable<short> RawMaterialCutType { get; set; }
        public Nullable<double> HeadPartLength { get; set; }
        public Nullable<double> TailPartLength { get; set; }
        public Nullable<double> HeadPartCumm { get; set; }
        public Nullable<double> TailPartCumm { get; set; }
        public Nullable<double> Elongation { get; set; }
        public Nullable<double> MotherOffset { get; set; }
        public Nullable<double> RelLength { get; set; }
        public Nullable<long> FeatureId { get; set; }
        public string RawMaterialName { get; set; }
        public string AssetName { get; set; }
        public string FeatureName { get; set; }
    }
}
