//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RollsWithTypes
    {
        public long RollId { get; set; }
        public string RollName { get; set; }
        public short Status { get; set; }
        public long RollTypeId { get; set; }
        public string RollTypeName { get; set; }
        public double ActualDiameter { get; set; }
        public double InitialDiameter { get; set; }
        public Nullable<double> MinimumDiameter { get; set; }
        public string Supplier { get; set; }
        public short GroovesNumber { get; set; }
        public string RollTypeDescription { get; set; }
        public Nullable<double> DiameterMin { get; set; }
        public Nullable<double> DiameterMax { get; set; }
        public Nullable<double> RoughnessMin { get; set; }
        public Nullable<double> RoughnessMax { get; set; }
        public Nullable<double> YieldStrengthRef { get; set; }
        public string SteelgradeRoll { get; set; }
        public Nullable<double> Length { get; set; }
        public string RollSetUpper { get; set; }
        public string RollSetBottom { get; set; }
        public Nullable<short> ScrapReason { get; set; }
        public Nullable<System.DateTime> ScrapDate { get; set; }
        public string RollDescription { get; set; }
        public Nullable<long> RollSetIdUpper { get; set; }
        public Nullable<long> RollSetIdBottom { get; set; }
        public Nullable<long> RollSetIdThird { get; set; }
        public long FKRollTypeId { get; set; }
        public Nullable<short> RollType { get; set; }
        public string RollSetThird { get; set; }
        public Nullable<short> MatchingRollsetType { get; set; }
    }
}
