//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RollHistoryPerGroove
    {
        public long RollId { get; set; }
        public string RollName { get; set; }
        public long FKRollSetId { get; set; }
        public long RollSetHistoryId { get; set; }
        public Nullable<double> ActDiameter { get; set; }
        public short GrooveNumber { get; set; }
        public double AccWeight { get; set; }
        public Nullable<double> AccWeightLimit { get; set; }
        public long AccBilletCnt { get; set; }
        public short RollSetHistoryStatus { get; set; }
        public short GrooveStatus { get; set; }
        public string GrooveTemplateName { get; set; }
        public Nullable<System.DateTime> Mounted { get; set; }
        public Nullable<System.DateTime> Dismounted { get; set; }
    }
}
