//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RollsetInCassettes
    {
        public long RollSetId { get; set; }
        public string RollSetName { get; set; }
        public Nullable<long> FKUpperRollId { get; set; }
        public Nullable<long> FKBottomRollId { get; set; }
        public short Status { get; set; }
        public short RollSetType { get; set; }
        public Nullable<long> FKCassetteId { get; set; }
        public short RollSetHistoryStatus { get; set; }
        public Nullable<short> PositionInCassette { get; set; }
        public Nullable<System.DateTime> Mounted { get; set; }
        public Nullable<System.DateTime> Dismounted { get; set; }
        public short CassetteStatus { get; set; }
        public string CassetteName { get; set; }
        public Nullable<long> FKStandId { get; set; }
        public Nullable<short> StandNo { get; set; }
    }
}
