//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RollsetOverviewNewest
    {
        public long RollSetId { get; set; }
        public short RollSetStatus { get; set; }
        public short RollSetType { get; set; }
        public string RollSetName { get; set; }
        public Nullable<long> RollIdUpper { get; set; }
        public Nullable<double> DiameterUpper { get; set; }
        public string RollNameUpper { get; set; }
        public Nullable<long> RollTypeIdUpper { get; set; }
        public string RollTypeUpper { get; set; }
        public Nullable<long> RollIdBottom { get; set; }
        public Nullable<double> DiameterBottom { get; set; }
        public string RollNameBottom { get; set; }
        public Nullable<long> RollTypeIdBottom { get; set; }
        public string RollTypeBottom { get; set; }
        public long RollSetHistoryId { get; set; }
        public short RollSetHistoryStatus { get; set; }
        public Nullable<long> CassetteId { get; set; }
        public string CassetteName { get; set; }
        public Nullable<short> PositionInCassette { get; set; }
        public Nullable<short> StandNo { get; set; }
        public Nullable<System.DateTime> Mounted { get; set; }
        public Nullable<System.DateTime> Dismounted { get; set; }
        public Nullable<short> CassetteStatus { get; set; }
        public Nullable<long> RollIdThird { get; set; }
        public Nullable<double> DiameterThird { get; set; }
        public string RollNameThird { get; set; }
        public Nullable<long> RollTypeIdThird { get; set; }
        public string RollTypeThird { get; set; }
        public Nullable<short> IsThirdRoll { get; set; }
        public Nullable<long> StandId { get; set; }
        public Nullable<short> IsOnLine { get; set; }
        public Nullable<long> FKCassetteTypeId { get; set; }
        public short Status { get; set; }
        public Nullable<long> FKCassetteId { get; set; }
        public Nullable<short> Type { get; set; }
    }
}
