//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RSCassettesInStands
    {
        public long StandId { get; set; }
        public short Status { get; set; }
        public short StandNo { get; set; }
        public string StandZoneName { get; set; }
        public Nullable<short> IsOnLine { get; set; }
        public Nullable<short> Position { get; set; }
        public Nullable<long> CassetteId { get; set; }
        public Nullable<short> CassetteStatus { get; set; }
        public string CassetteName { get; set; }
        public Nullable<short> Arrangement { get; set; }
        public string CassetteTypeName { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<long> CassetteTypeId { get; set; }
    }
}
