//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TriggerOverview
    {
        public long Sorting { get; set; }
        public string TriggerCode { get; set; }
        public string TriggerName { get; set; }
        public bool IsActive { get; set; }
        public string EnumKeyword { get; set; }
        public int FeatureCode { get; set; }
        public string FeatureName { get; set; }
        public string AssetCode { get; set; }
        public string AssetName { get; set; }
        public short PassNo { get; set; }
        public string Relations { get; set; }
    }
}
