//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.DbEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WorkOrderSummary
    {
        public long Sorting { get; set; }
        public long WorkOrderId { get; set; }
        public string WorkOrderName { get; set; }
        public bool IsTestOrder { get; set; }
        public short WorkOrderStatus { get; set; }
        public string ProductCatalogueName { get; set; }
        public string MaterialCatalogueName { get; set; }
        public string HeatName { get; set; }
        public string SteelgradeCode { get; set; }
        public System.DateTime CreatedInL3 { get; set; }
        public System.DateTime ToBeCompletedBefore { get; set; }
        public Nullable<long> ScheduleId { get; set; }
        public Nullable<System.DateTime> PlannedStartTime { get; set; }
        public Nullable<System.DateTime> PlannedEndTime { get; set; }
        public Nullable<System.DateTime> ProductionStart { get; set; }
        public Nullable<System.DateTime> ProductionEnd { get; set; }
        public double TargetOrderWeight { get; set; }
        public double ProductsWeight { get; set; }
        public Nullable<double> MaterialsWeight { get; set; }
        public Nullable<double> MetallicYield { get; set; }
        public double Completion { get; set; }
        public int ProductsNumber { get; set; }
        public Nullable<int> MaterialsPlanned { get; set; }
        public Nullable<int> MaterialsAssigned { get; set; }
        public Nullable<int> MaterialsCharged { get; set; }
        public Nullable<int> MaterialsDischarged { get; set; }
        public Nullable<int> MaterialsRolled { get; set; }
        public Nullable<int> MaterialsRejected { get; set; }
        public Nullable<int> MaterialsScrapped { get; set; }
        public int IsProducedNow { get; set; }
        public int IsPlanned { get; set; }
        public Nullable<short> ScheduleOrderSeq { get; set; }
    }
}
