CREATE TABLE [xfr].[ProductCatalogueTT] (
    [ProductCatalogueName]       NVARCHAR (255) NULL,
    [IsActive]                   SMALLINT       NULL,
    [IsDefault]                  SMALLINT       NULL,
    [Description]                NVARCHAR (255) NULL,
    [SAPNumber]                  NVARCHAR (255) NULL,
    [Length]                     FLOAT (53)     NULL,
    [LengthMin]                  FLOAT (53)     NULL,
    [LengthMax]                  FLOAT (53)     NULL,
    [Thickness]                  FLOAT (53)     NULL,
    [ThicknessMin]               FLOAT (53)     NULL,
    [ThicknessMax]               FLOAT (53)     NULL,
    [Width]                      FLOAT (53)     NULL,
    [WidthMin]                   FLOAT (53)     NULL,
    [WidthMax]                   FLOAT (53)     NULL,
    [Weight]                     FLOAT (53)     NULL,
    [WeightMin]                  FLOAT (53)     NULL,
    [WeightMax]                  FLOAT (53)     NULL,
    [Slitting]                   FLOAT (53)     NULL,
    [ExitSpeed]                  FLOAT (53)     NULL,
    [StdMetallicYield]           FLOAT (53)     NULL,
    [StdQualityYield]            FLOAT (53)     NULL,
    [StdGapTime]                 FLOAT (53)     NULL,
    [StdRollingTime]             FLOAT (53)     NULL,
    [StdUtilizationTime]         FLOAT (53)     NULL,
    [StdProductionTime]          FLOAT (53)     NULL,
    [StdProductivity]            FLOAT (53)     NULL,
    [MaxTensile]                 FLOAT (53)     NULL,
    [MaxYieldPoint]              FLOAT (53)     NULL,
    [Ovality]                    FLOAT (53)     NULL,
    [MaxOvality]                 FLOAT (53)     NULL,
    [ProfileToleranceMin]        FLOAT (53)     NULL,
    [ProfileToleranceMax]        FLOAT (53)     NULL,
    [ShapeSymbol]                NVARCHAR (255) NULL,
    [SteelgradeCode]             NVARCHAR (255) NULL,
    [ProductCatalogueTypeSymbol] NVARCHAR (255) NULL
);

