CREATE VIEW [dbo].[V_DW_DimSteelgrade]
AS
     SELECT CAST('PE_Lite' AS NVARCHAR(50)) AS DataSource, 
            CONVERT(DATETIME2(3), SYSDATETIME()) AS ValidFrom, 
            CONVERT(DATETIME2(3), '99991231 23:59:59.999') AS ValidTo, 
            S.SteelgradeId AS DimSteelgradeKey, 
            S.ParentSteelgradeId AS DimParentSteelgradeKey, 
            S.SteelgradeCode, 
            S.SteelgradeName, 
            SteelgradeDescription, 
            CAST(S.Density AS NUMERIC(18, 8)) AS SteelgradeDensity, 
            CAST(S.OvenRecipeTemperature AS NUMERIC(18, 8)) AS SteelgradeOvenRecipeTemperature, 
            S.QualitySpecification AS SteelgradeQualitySpecification, 
            S.CommercialGroup AS SteelgradeCommercialGroup, 
            S.CustomerUseCode AS SteelgradeCustomerUseCode, 
            S.CustomerUseDescription AS SteelgradeCustomerUseDescription, 
            SG.SteelGroupCode AS SteelGroupCode, 
            SG.SteelGroupName AS SteelGroupName, 
            SG.SteelGroupDescription AS SteelGroupDescription, 
            CAST(SCC.FeMin AS NUMERIC(18, 8)) AS SteelgradeFeMin, 
            CAST(SCC.FeMax AS NUMERIC(18, 8)) AS SteelgradeFeMax, 
            CAST(SCC.CMin AS NUMERIC(18, 8)) AS SteelgradeCMin, 
            CAST(SCC.CMax AS NUMERIC(18, 8)) AS SteelgradeCMax, 
            CAST(SCC.MnMin AS NUMERIC(18, 8)) AS SteelgradeMnMin, 
            CAST(SCC.MnMax AS NUMERIC(18, 8)) AS SteelgradeMnMax, 
            CAST(SCC.CrMin AS NUMERIC(18, 8)) AS SteelgradeCrMin, 
            CAST(SCC.CrMax AS NUMERIC(18, 8)) AS SteelgradeCrMax, 
            CAST(SCC.MoMin AS NUMERIC(18, 8)) AS SteelgradeMoMin, 
            CAST(SCC.MoMax AS NUMERIC(18, 8)) AS SteelgradeMoMax, 
            CAST(SCC.VMin AS NUMERIC(18, 8)) AS SteelgradeVMin, 
            CAST(SCC.VMax AS NUMERIC(18, 8)) AS SteelgradeVMax, 
            CAST(SCC.NiMin AS NUMERIC(18, 8)) AS SteelgradeNiMin, 
            CAST(SCC.NiMax AS NUMERIC(18, 8)) AS SteelgradeNiMax, 
            CAST(SCC.CoMin AS NUMERIC(18, 8)) AS SteelgradeCoMin, 
            CAST(SCC.CoMax AS NUMERIC(18, 8)) AS SteelgradeCoMax, 
            CAST(SCC.SiMin AS NUMERIC(18, 8)) AS SteelgradeSiMin, 
            CAST(SCC.SiMax AS NUMERIC(18, 8)) AS SteelgradeSiMax, 
            CAST(SCC.PMin AS NUMERIC(18, 8)) AS SteelgradePMin, 
            CAST(SCC.PMax AS NUMERIC(18, 8)) AS SteelgradePMax, 
            CAST(SCC.SMin AS NUMERIC(18, 8)) AS SteelgradeSMin, 
            CAST(SCC.SMax AS NUMERIC(18, 8)) AS SteelgradeSMax, 
            CAST(SCC.CuMin AS NUMERIC(18, 8)) AS SteelgradeCuMin, 
            CAST(SCC.CuMax AS NUMERIC(18, 8)) AS SteelgradeCuMax, 
            CAST(SCC.NbMin AS NUMERIC(18, 8)) AS SteelgradeNbMin, 
            CAST(SCC.NbMax AS NUMERIC(18, 8)) AS SteelgradeNbMax, 
            CAST(SCC.AlMin AS NUMERIC(18, 8)) AS SteelgradeAlMin, 
            CAST(SCC.AlMax AS NUMERIC(18, 8)) AS SteelgradeAlMax, 
            CAST(SCC.NMin AS NUMERIC(18, 8)) AS SteelgradeNMin, 
            CAST(SCC.NMax AS NUMERIC(18, 8)) AS SteelgradeNMax, 
            CAST(SCC.CaMin AS NUMERIC(18, 8)) AS SteelgradeCaMin, 
            CAST(SCC.CaMax AS NUMERIC(18, 8)) AS SteelgradeCaMax, 
            CAST(SCC.BMin AS NUMERIC(18, 8)) AS SteelgradeBMin, 
            CAST(SCC.BMax AS NUMERIC(18, 8)) AS SteelgradeBMax, 
            CAST(SCC.TiMin AS NUMERIC(18, 8)) AS SteelgradeTiMin, 
            CAST(SCC.TiMax AS NUMERIC(18, 8)) AS SteelgradeTiMax, 
            CAST(SCC.SnMin AS NUMERIC(18, 8)) AS SteelgradeSnMin, 
            CAST(SCC.SnMax AS NUMERIC(18, 8)) AS SteelgradeSnMax, 
            CAST(SCC.OMin AS NUMERIC(18, 8)) AS SteelgradeOMin, 
            CAST(SCC.OMax AS NUMERIC(18, 8)) AS SteelgradeOMax, 
            CAST(SCC.HMin AS NUMERIC(18, 8)) AS SteelgradeHMin, 
            CAST(SCC.HMax AS NUMERIC(18, 8)) AS SteelgradeHMax, 
            CAST(SCC.WMin AS NUMERIC(18, 8)) AS SteelgradeWMin, 
            CAST(SCC.WMax AS NUMERIC(18, 8)) AS SteelgradeWMax, 
            CAST(SCC.PbMin AS NUMERIC(18, 8)) AS SteelgradePbMin, 
            CAST(SCC.PbMax AS NUMERIC(18, 8)) AS SteelgradePbMax, 
            CAST(SCC.ZnMin AS NUMERIC(18, 8)) AS SteelgradeZnMin, 
            CAST(SCC.ZnMax AS NUMERIC(18, 8)) AS SteelgradeZnMax, 
            CAST(SCC.AsMin AS NUMERIC(18, 8)) AS SteelgradeAsMin, 
            CAST(SCC.AsMax AS NUMERIC(18, 8)) AS SteelgradeAsMax, 
            CAST(SCC.MgMin AS NUMERIC(18, 8)) AS SteelgradeMgMin, 
            CAST(SCC.MgMax AS NUMERIC(18, 8)) AS SteelgradeMgMax, 
            CAST(SCC.SbMin AS NUMERIC(18, 8)) AS SteelgradeSbMin, 
            CAST(SCC.SbMax AS NUMERIC(18, 8)) AS SteelgradeSbMax, 
            CAST(SCC.BiMin AS NUMERIC(18, 8)) AS SteelgradeBiMin, 
            CAST(SCC.BiMax AS NUMERIC(18, 8)) AS SteelgradeBiMax, 
            CAST(SCC.TaMin AS NUMERIC(18, 8)) AS SteelgradeTaMin, 
            CAST(SCC.TaMax AS NUMERIC(18, 8)) AS SteelgradeTaMax, 
            CAST(SCC.ZrMin AS NUMERIC(18, 8)) AS SteelgradeZrMin, 
            CAST(SCC.ZrMax AS NUMERIC(18, 8)) AS SteelgradeZrMax, 
            CAST(SCC.CeMin AS NUMERIC(18, 8)) AS SteelgradeCeMin, 
            CAST(SCC.CeMax AS NUMERIC(18, 8)) AS SteelgradeCeMax, 
            CAST(SCC.TeMin AS NUMERIC(18, 8)) AS SteelgradeTeMin, 
            CAST(SCC.TeMax AS NUMERIC(18, 8)) AS SteelgradeTeMax
     FROM dbo.PRMSteelgrades AS S
          LEFT JOIN dbo.PRMSteelGroups SG ON S.FKSteelGroupId = SG.SteelGroupId
          LEFT JOIN dbo.PRMSteelgradeChemicalCompositions SCC ON S.SteelgradeId = SCC.FKSteelgradeId;